### ISSUE TITLE
Error installing using Docker on ARM Linux platforms

### ISSUE THREAD

**Issue by dummyusercenor** [silveredgold/beta-censoring#10]
First of all, great app! Working perfectly on M2 Mac, once you allow the services to run from under Settings > Security and Privacy. 

I am now trying to install it using a docker container on a raspberrypi, however it gives me the below error. 

`standard_init_linux.go:211: exec user process caused "exec format error"`

Your help is much appreciated. Thanks!

**Comment by silveredgold** [comment]
There is no ARM build available for the Docker image at this time. Since I don't have a Pi to test with (and they're hard to get hold of right now), I can't really support non-x64 Linux platforms.

If I can get hold of a Pi, I'll look into adding an ARM build for Linux.
