### ISSUE TITLE
how to turn off image blocking or only add a blur?

### ISSUE THREAD

**Issue by ennuirose** [silveredgold/beta-censoring#16]
beta censoring blocks the image entirely from loading, can this be replaced with a blur from the settings just like videos?

**Comment by silveredgold** [comment]
What do you mean by blocks the image? The image is only temporarily blocked while the censoring takes place and it will be replaced by the censored image as each image is complete.

If you only want blurring as a censoring, set your censoring preferences in the extension options to use "Blur"
