### ISSUE TITLE
Backend error

### ISSUE THREAD

**Issue by darknest1** [silveredgold/beta-censoring#17]
Hi! Getting an error whenever I attempt to process an image. I have installed the RTP as requested but it's still not finding two of the DLLs. Any help would be greatly appreciated :)

![Screenshot_6](https://user-images.githubusercontent.com/122267396/211280078-c29c63e6-0545-48b2-a1c8-cd02303ae25b.png)

**Comment by silveredgold** [comment]
What platform are you on?
