### ISSUE TITLE
Problem with import files

### ISSUE THREAD

**Issue by ShiranuiBigBoing** [silveredgold/beta-censoring#19]
Hi. I have a problem when i try to import a folder of images to censor in Brave browser.
![Screenshot_101](https://user-images.githubusercontent.com/91887019/212498504-a9d2e4a9-3151-4163-adf0-f3ac490f181f.png)

**Comment by silveredgold** [comment]
As covered in the [Installation troubleshooting guide](https://silveredgold.github.io/beta-protection/guide/installation.html#can-t-import-placeholders-or-censor-local-images-with-brave), the Brave developers have turned off the ability for extensions to load local files. 

There's nothing I can do about this, Brave is the only Chrome-based browser that does this.

**Comment by nsfwdev255** [comment]
Just wanted to chime in here to add some instructions for people who want to enable this in Brave, it took some digging on my end. Made a github alt just to contribute to this lol.

Perhaps @silveredgold could add this to the docs.

Instructions found at `https://github.com/brave/brave-browser/issues/18979`:

1. Navigate to `brave://flags`
2. In the search box type `file-system-access-api`
3. Change the File System API item's status to `Enabled`
4. Click on the `Relaunch` button
5. Once the browser restarts, the `Import Files...` button in the Beta Protection Extension UI should work.
