### ISSUE TITLE
Documentation for censoring configuration options

### ISSUE THREAD

**Issue by Totobidonxxx** [silveredgold/beta-censoring#23]
Hi do you have a config.json already made? like you just need to change file location or a tuto for made one from scratch for a newbe.

**Comment by ortecow** [comment]
Yeah Yeah the docs don't cover everything. It doesn't mention anything about CensorOptions, and I can't figure out how to use it.

**Comment by silveredgold** [comment]
Not all the configuration flags are documented as they tend to be used for non-standard scenarios that many users won't need. I already have issues with people not reading the documentation as it is, so I've generally preferred to keep it as simple as possible. I'll look into fleshing out the docs for some of the extra configuration options.

**Comment by silveredgold** [comment]
@desdequetevi We can't really expose these settings in Beta Protection for two reasons:

1) There's currently no API for the server to update its own configuration (so no way for the extension to set those values), and
2) Not all extension users are using Beta Censoring as a backend so those options wouldn't work for anyone using other backends.
