### ISSUE TITLE
wont run

### ISSUE THREAD

**Issue by striker565** [silveredgold/beta-censoring#25]
- the server wont run , downloaded properly , extracted and wont run or open. what to do

**Comment by silveredgold** [comment]
I would need more information to help here.

**Comment by rrrr141** [comment]
server won`t run, no connection to backend, how i can get run backend?

**Comment by silveredgold** [comment]
That does not help at all. I need details of what backend you are using, what happens when you run it, what platform you are on, what you have tried etc. If you can provide that info, I might be able to help.
