### ISSUE TITLE
Cannot change listening port for server

### ISSUE THREAD

**Issue by silveredgold** [silveredgold/beta-censoring#33]
If something else is using port 2382, there's currently no way to change what port the server runs on. We might want the option to change this, but also don't want to surface this too obviously as it's not something anyone should be changing unless they really have to.

Raised in silveredgold/beta-protection#56

**Comment by lxb123** [comment]
How to change the startup port?

**Comment by silveredgold** [comment]
How are you running the server? You should be able to change the listening
URL with either the `ASPNETCORE_URLS` environment variable, or the `--urls`
CLI, providing something like "http://*:80/" as a value.
