### ISSUE TITLE
Bad CPU type after trying to set as executable MacOS Ventura 13.6

### ISSUE THREAD

**Issue by extantmoose** [silveredgold/beta-censoring#35]
christopher@ChristophersAir ~ % /Users/christopher/Documents/BetaServer/betacensor-server-osx.10.14-x64 sudo chmod +x betacensor-server-osx.10.14-x64/BetaCensor.Server

zsh: permission denied: /Users/christopher/Documents/BetaServer/betacensor-server-osx.10.14-x64
christopher@ChristophersAir ~ % cd /Users/christopher/Documents/BetaServer/betacensor-server-osx.10.14-x64

christopher@ChristophersAir betacensor-server-osx.10.14-x64 % sudo chmod +x BetaCensor.Server

Password:
christopher@ChristophersAir betacensor-server-osx.10.14-x64 % ./BetaCensor.Server
zsh: bad CPU type in executable: ./BetaCensor.Server
christopher@ChristophersAir betacensor-server-osx.10.14-x64 % 

I'm on a 2020 M1 Macbook Air running Ventura 13.6. Now, I was literally running this a few days ago (on 13.6), yesterday, on SONOMA. And sonoma f'd up a ton of stuff for me (tkinter totally shit the bed? weird) so i rolled it back today. But I'm STILL getting this 'bad cpu type' error. 

Any thoughts? I've run the gamut of things to try, honestly. I can't figure out what's going on, why it worked before, or how/if I'm doing anything different now.. friggan macs.

**Comment by extantmoose** [comment]
Well... ended up fooling around a ton, ran it different way Last login: Sat Oct 14 22:45:00 on ttys000
christopher@ChristophersAir ~ % cd /Users/christopher/Documents/BetaServer/betacensor-server-osx.10.14-x64
./BetaCensor.Server

got it working. sorry! boy that was puzzling

**Comment by silveredgold** [comment]
If I had to guess, that's probably #3 rearing its head again. Apple really makes the Apple Silicon (i.e. M1/M2) hardware difficult to provide software for unless you're willing to play by their rules (which I am not).

Glad you got it worked out in the end!

**Comment by extantmoose** [comment]
I can't blame you for not bothering to play ball. On a hobby-level project like this, what a headache Apple creates. Appreciate what you do @silveredgold. I'm gonna be putting some of my own things together, I'm pretty much only savvy with python, let me know if I can ever be of assistance!
