### ISSUE TITLE
Failed to load AI model

### ISSUE THREAD

**Issue by ghost** [silveredgold/beta-censoring#39]
Hi, I've been struggling with this for a while and can't find a solution anywhere. I was wondering if you could help me?

Upon double clicking the 'BetaCensor.Server.exe' I keep getting this error:

Unhandled exception. System.IO.InvalidDataException: Failed to retrieve AI model! Aborting...
   at Program.<Main>$(String[] args) in /home/runner/work/beta-censoring/beta-censoring/src/BetaCensor.Server/Program.cs:line 40
   at Program.<Main>(String[] args)

I have pip installed the nude net model and can't think of what else to do?

**Comment by Bergamerikana** [comment]
same

**Comment by OuterReach23** [comment]
The owner of the project notAI-tech/NudeNet provided and updated release breaking the method used for loading the AI model resource. 
The project looks for the .onnx model that the BetaCensor.Server.exe runs from in three locations, the git repo, the .exe native directory and the user/temp/.nudenet directory.  The second issue is that severe censor core seems to only run as compiled on file (https://github.com/notAI-tech/NudeNet/releases/download/v0/detector_v2_default_checkpoint.onnx).

The simple fix is to download the onnx file "detector_v2_default_checkpoint.onnx" and paste it into the directory that BetaCensor.Server.exe runs from

**Comment by ghost** [comment]
Thank you, this worked perfectly

**Comment by jesseluvsheels** [comment]
Perfect!!! thank you so much!

**Comment by BetaFemboy69** [comment]
thank you
