### ISSUE TITLE
Hide your terminal :)

### ISSUE THREAD

**Issue by ThisGirlLise** [silveredgold/beta-censoring#4]
Did you know, that you can hide your terminal window and thus not have the terminal window open on your taskbar or the icon in the notification area?

`Start-Process -FilePath ".\BetaCensor.Server.exe" -WindowStyle Hidden`

this does that trick :)

**Comment by silveredgold** [comment]
I personally run mine as a service instead of running it in the foreground, but that's a good tip for people who don't want to set that up, I'll add it to the docs at some point.

**Comment by x2stla** [comment]
can you help me set this up? when i try it, its simply not connecting to the backend anymore
