### ISSUE TITLE
Server fails to start on mac OS when blocked by Gatekeeper

### ISSUE THREAD

**Issue by DiscoverySub** [silveredgold/beta-censoring#5]
Hi.
I'm on Mac using v0.0.8.
I'm getting the following error in my terminal "Register your handlers with the container". It says see samples on github, but I cannot see them.
At the moment I'm just getting the placeholder loading image and nothing actually gets fully censored as it should. I assume it's to do with this error.
Any advice would be great.
Thanks
DS

**Comment by silveredgold** [comment]
Sorry about the delay getting to this, missed the email. I need to see the actual error text to tell you what the problem is, and also need to know what platform you are on.

**Comment by DiscoverySub** [comment]
Hi. Thanks for getting back to me. 
I'm on Mac. I've attached the error.
[BC error.txt](https://github.com/silveredgold/beta-censoring/files/9550072/BC.error.txt)

**Comment by silveredgold** [comment]
If I had to guess, it looks like you haven't allowed the server in the macOS privacy/security settings. Since I didn't pay Apple for a certificate etc, the OS will block the server from loading what it needs to run.

Have you definitely allowed the server from the security warnings as per the instructions [here](https://silveredgold.github.io/beta-censoring/content/installation.html#macos)

**Comment by DiscoverySub** [comment]
I think you're right in that it's that that's stopping it, however once it's running and I go to System preferences>Security and Privacy>Privacy there is nothing there that prompts me to allow it. I've checked it numerous times (after closing the terminal, leaving the terminal running, enabling beta protection etc) but there is never the option your instructions refer to.

**Comment by silveredgold** [comment]
As I don't own a Mac and Apple don't allow running mac OS on non-Apple hardware, I can't exactly help too much, but you'll need to allow the server to load the files it needs (in this case, the AI runtime).

I've successfully tested this a while back on a Mac running Monterey and I've had reports of it running successfully on newer versions as well.

**Comment by DiscoverySub** [comment]
I understand, not a problem. I've managed to get the security and privacy area to prompt to allow the app a couple of times, but it doesn't consistently prompt for this or seem to hold the setting. Even once allowed, I still get the spinning over images and errors within the terminal session.
I'm happy for you to close the issue if you like, as it's difficult to troubleshoot it further.
Cheers.
